# Generated by Django 5.1.15 on 2026-03-28 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_visit',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.visit')),
            ],
            options={
                'db_table': 'analytics_pageview',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Visita al sitio'), ('product_view', 'Vista de producto'), ('add_to_cart', 'Agregar al carrito'), ('checkout_start', 'Inicio de checkout'), ('purchase', 'Compra completada')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_events', to='analytics.visit')),
            ],
            options={
                'db_table': 'analytics_funnelevent',
                'ordering': ['-timestamp'],
            },
        ),
    ]
