# Generated by Django 5.1.15 on 2026-03-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_production', 'En producción'), ('completed', 'Completado')], default='pending', max_length=20)),
                ('estimated_completion', models.DateField(blank=True, null=True, verbose_name='Fecha estimada')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_tickets', to='orders.orderitem')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_tickets', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'Ticket de producción',
                'verbose_name_plural': 'Tickets de producción',
                'db_table': 'production_productionticket',
            },
        ),
    ]
