# Generated by Django 5.1.15 on 2026-03-28 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Número de guía')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Paquetería')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Enviado'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ship_ticket', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ticket de envío',
                'verbose_name_plural': 'Tickets de envío',
                'db_table': 'shipping_shipticket',
            },
        ),
    ]
